name: Build and release PDF

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install pandoc texlive-latex-base texlive-xetex fonts-inter

      - name: Build PDF
        run: |
          ./pdf/build.sh
          echo "GENERATED_DATE=$GENERATED_DATE" >> "$GITHUB_ENV"
          echo "REVIEW_DATE=$REVIEW_DATE" >> "$GITHUB_ENV"

      - name: Create release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create release-${{ github.sha }} \
            --notes "PDF generated: $GENERATED_DATE\nLast major curriculum review: $REVIEW_DATE" \
            --target ${{ github.sha }} \
            --title $GENERATED_DATE \
            pdf/MDN-Curriculum.pdf
