name: Build and release PDF

on:
  push:
    branches:
      - main
      - pdf-test

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get install pandoc texlive-latex-base texlive-xetex fonts-inter

      - name: Build PDF
        run: |
          ./pdf/build.sh

      - name: Set release dates
        run: |
          echo "MAJOR_DATE=`cat LAST_MAJOR_REVIEW.txt`" >> "$GITHUB_ENV"
          echo "MINOR_DATE=`date -u '+%Y-%m-%d'`" >> "$GITHUB_ENV"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: pdf/MDN-Curriculum.pdf
          commit: ${{ github.sha }}
          tag: ${{ github.sha }}
          body: |
            Last major curriculum review: ${{ env.MAJOR_DATE }}. PDF generated: ${{ env.MINOR_DATE }}.
